### ISSUE TITLE
If i type "node server.js" these erros will be appeared. I type "node server.js" after typing "npm start"

### ISSUE THREAD

**Issue by nodvos** [54017/omegle#1]
$ node server.js
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at Server.listen (net.js:1476:7)
    at C:\xampp\htdocs\server.js:16:7
    at Object.<anonymous> (C:\xampp\htdocs\server.js:105:2)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)

  If I click on start chatting button it can't find me stranger. I use smartphone and laptop for chatting

**Comment by nodvos** [comment]
How to fix it?

**Comment by 54017** [comment]
@nodvos https://stackoverflow.com/questions/4075287/node-express-eaddrinuse-address-already-in-use-kill-server Hope it can help you
